Repository artichoke/strftime-ruby, pull requests merged in 2022-08, with the labels that each got.

#10 chore: Update `.github/workflows/rustdoc.yaml` in `artichoke/strftime…
  .github/workflows/rustdoc.yaml
Labels: A-build, C-docs

#13 Ensure MSRV CI job overrides the active Rust version
  .github/workflows/ci.yaml
Labels: A-build

#15 Update MSRV to 1.58.0
  .github/workflows/ci.yaml
  Cargo.toml
  README.md
Labels: A-crate-features, A-deps

#12 Implement strftime
  Cargo.toml
  LICENSE
  README.md
  src/format/assert.rs
  src/format/mod.rs
  src/format/utils.rs
  src/format/week.rs
  src/format/write.rs
  src/lib.rs
  src/mock.rs.in
  src/tests.rs
Labels: A-formatter, A-parser

#16 Fix link to GitHub Pages docs in README
  README.md
Labels: A-project, C-docs

#17 Doc and Rust comment fixups
  .config/artichoke.dic
  .config/spellcheck.toml
  .gitignore
  src/format/mod.rs
  src/format/week.rs
  src/format/write.rs
  src/lib.rs
Labels: C-docs

#18 Fixup no-std support so the crate builds with only alloc feature
  .github/workflows/ci.yaml
  src/format/write.rs
  src/lib.rs
  src/tests.rs
Labels: A-build, A-crate-features

#19 Update tests to not require that `Error` derives `Copy`
  src/mock.rs.in
  src/tests.rs
Labels: C-quality

#20 Use fallible allocation APIs
  src/format/write.rs
  src/lib.rs
  src/tests.rs
Labels: A-formatter, C-quality

#23 Add some more README docs on implications of Cargo features
  README.md
Labels: A-crate-features, C-docs

#25 Remove unused quickcheck dev dependencies
  Cargo.toml
Labels: A-deps

#37 Add code coverage workflow which uploads to S3
  .github/workflows/code-coverage.yaml
  README.md
Labels: A-build

#36 Add tests for trait implementations on `strftime::Error`
  src/format/utils.rs
  src/format/write.rs
  src/lib.rs
  src/tests/error.rs
  src/tests/format.rs
  src/tests/mod.rs
Labels: C-quality

#39 Add Time#asctime format string constant
  src/lib.rs
Labels: A-formatter

#47 Add note about implementing `Time` trait to crate-level documentation
  src/lib.rs
Labels: C-docs

#49 Provide a std::io::Write strftime implementation
  src/format/check.rs
  src/format/mod.rs
  src/format/write.rs
  src/lib.rs
  src/tests/error.rs
  src/tests/format.rs
Labels: A-formatter

#50 Provide a core::fmt::Write strftime implementation
  src/format/mod.rs
  src/format/write.rs
  src/lib.rs
  src/tests/error.rs
Labels: A-formatter

#54 Make mod-level docs have consistent structure
  src/lib.rs
Labels: C-docs

#56 Clarify license of vendored Ruby C code
  Cargo.toml
  README.md
  vendor/README.md
  vendor/ruby-3.1.2/BSDL
Labels: A-packaging, A-project

#57 Fix a typo in strftime::buffered module docs
  src/lib.rs
Labels: C-docs

#59 Fix link check exclude to allow README in top of vendor directory
  Rakefile
Labels: C-docs

#60 Add new words to spellcheck dictionary
  .config/artichoke.dic
Labels: C-docs, C-quality

#61 Propagate inner core::fmt::Error
  src/format/write.rs
  src/lib.rs
  src/tests/error.rs
Labels: A-formatter, C-quality

#63 Add coverage for `fmt::Debug` impl on `Error`
  src/tests/error.rs
Labels: C-quality

#65 Add tests for Debug impls on all internal structs and enums
  src/format/mod.rs
  src/format/utils.rs
  src/format/week.rs
  src/tests/error.rs
Labels: C-quality

#62 Add a test for a larger format string with non-specifier contents
  src/tests/format.rs
Labels: A-formatter, C-quality

#55 Add better README descriptions of what each cargo feature activates
  README.md
Labels: C-docs

#58 Prepare for v1.0.0 release
  Cargo.toml
  README.md
  src/lib.rs
Labels: A-release

#67 Add tests for check format assertions
  .gitignore
  src/tests/format.rs
Labels: C-quality

#68 chore: Update `.github/workflows/code-coverage.yaml` in `artichoke/st…
  .github/workflows/code-coverage.yaml
Labels: A-build

#70 chore: Update `.github/workflows/code-coverage.yaml` in `artichoke/st…
  .github/workflows/code-coverage.yaml
Labels: A-build

#71 chore: Update `.github/workflows/code-coverage.yaml` in `artichoke/st…
  .github/workflows/code-coverage.yaml
Labels: A-build
